from src.schemas.ai import (
    AIConversationCreate,
    AIConversationResponse,
    AIConversationUpdate,
    AIMessageCreate,
    AIMessageResponse,
    PromptTemplateCreate,
    PromptTemplateResponse,
    PromptTemplateUpdate,
    PromptVersionCreate,
    PromptVersionResponse,
    RecommendationCreate,
    RecommendationFeedbackCreate,
    RecommendationFeedbackResponse,
    RecommendationResponse,
)
from src.schemas.auth import (
    TokenRefreshRequest,
    TokenResponse,
    UserLoginRequest,
    UserRegisterRequest,
)
from src.schemas.goal import UserGoalCreateRequest, UserGoalResponse
from src.schemas.meal import (
    DailySummaryResponse,
    MealCreateRequest,
    MealItemCreate,
    MealItemResponse,
    MealResponse,
    MealUpdateRequest,
    WeeklySummaryResponse,
)
from src.schemas.nutrition import (
    BarcodeProductResponse,
    FavoriteFoodResponse,
    FoodCategoryResponse,
    FoodResponse,
    NutritionFactResponse,
    RecentFoodResponse,
)
from src.schemas.profile import UserProfileResponse, UserProfileUpdateRequest
from src.schemas.user import UserDetailResponse, UserResponse
from src.schemas.weight import WeightLogCreateRequest, WeightLogResponse

__all__ = [
    "UserRegisterRequest",
    "UserLoginRequest",
    "TokenResponse",
    "TokenRefreshRequest",
    "UserResponse",
    "UserDetailResponse",
    "UserProfileUpdateRequest",
    "UserProfileResponse",
    "UserGoalCreateRequest",
    "UserGoalResponse",
    "WeightLogCreateRequest",
    "WeightLogResponse",
    "NutritionFactResponse",
    "FoodCategoryResponse",
    "FoodResponse",
    "BarcodeProductResponse",
    "FavoriteFoodResponse",
    "RecentFoodResponse",
    "MealItemCreate",
    "MealItemResponse",
    "MealCreateRequest",
    "MealUpdateRequest",
    "MealResponse",
    "DailySummaryResponse",
    "WeeklySummaryResponse",
    "AIMessageCreate",
    "AIMessageResponse",
    "AIConversationCreate",
    "AIConversationUpdate",
    "AIConversationResponse",
    "PromptVersionCreate",
    "PromptVersionResponse",
    "PromptTemplateCreate",
    "PromptTemplateUpdate",
    "PromptTemplateResponse",
    "RecommendationFeedbackCreate",
    "RecommendationFeedbackResponse",
    "RecommendationCreate",
    "RecommendationResponse",
]
